import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppColors } from '@/constants/theme';
import { api } from '@/lib/api';

const TIMEFRAMES = ['1m', '5m', '15m', '1h', '4h', '1d'];
const RISKS = ['low', 'medium', 'high'];
export default function TradeScreen() {
  const [symbols, setSymbols] = useState<string[]>([]); const [symbol, setSymbol] = useState('BTCUSDT'); const [tf, setTf] = useState('1m'); const [risk, setRisk] = useState('medium'); const [indicators, setIndicators] = useState<Record<string, number>>({}); const [running, setRunning] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(true);
  useEffect(() => { api.getMarkets().then((result) => { setSymbols(result.symbols); if (result.symbols[0]) setSymbol(result.symbols[0]); }).finally(() => setBusy(false)); }, []);
  useEffect(() => { api.getIndicators(symbol, tf).then((result) => setIndicators(result.indicators)).catch(() => setIndicators({})); }, [symbol, tf]);
  const start = () => { setMessage(''); api.startAgent({ symbol, risk, max_position_pct: 0.2, arm_live: false }).then(() => { setRunning(true); setMessage('Bob is running.'); }).catch(() => setMessage('Connect Bybit before starting Bob.')); };
  const stop = () => api.stopAgent().then(() => { setRunning(false); setMessage('Bob stopped.'); });
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Configure Bob</Text><Text style={styles.label}>ASSET</Text><View style={styles.wrap}>{(symbols.length ? symbols : ['BTCUSDT', 'ETHUSDT', 'SOLUSDT']).map((item) => <Pressable key={item} onPress={() => setSymbol(item)} style={[styles.chip, symbol === item && styles.chipSelected]}><Text style={styles.chipText}>{item}</Text></Pressable>)}</View><View style={styles.chart}><Text style={styles.chartSymbol}>{symbol}</Text><Text style={styles.chartHint}>{busy ? 'Loading market data…' : 'Live chart surface'}</Text><Text style={styles.price}>{indicators.ema20 ? indicators.ema20.toFixed(2) : '--'}</Text></View><View style={styles.wrap}>{TIMEFRAMES.map((item) => <Pressable key={item} onPress={() => setTf(item)} style={[styles.smallChip, tf === item && styles.chipSelected]}><Text style={styles.chipText}>{item}</Text></Pressable>)}</View><View style={styles.indicatorRow}><Text style={styles.muted}>RSI14 {indicators.rsi14?.toFixed(1) ?? '--'}</Text><Text style={styles.muted}>EMA20 {indicators.ema20?.toFixed(2) ?? '--'}</Text></View><Text style={styles.label}>RISK PROFILE</Text><View style={styles.wrap}>{RISKS.map((item) => <Pressable key={item} onPress={() => setRisk(item)} style={[styles.chip, risk === item && styles.chipSelected]}><Text style={styles.chipText}>{item}</Text></Pressable>)}</View>{message ? <Text style={styles.message}>{message}</Text> : null}<Pressable onPress={running ? stop : start} style={[styles.action, running && styles.stop]}><Text style={styles.actionText}>{running ? 'Stop Bob' : 'Start Bob'}</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: AppColors.background, padding: 20 }, content: { paddingBottom: 48 }, title: { color: '#fff', fontSize: 32, fontWeight: '700', marginTop: 16, marginBottom: 28 }, label: { color: AppColors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 1.4, marginTop: 18, marginBottom: 10 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderColor: AppColors.hairline, borderWidth: 1, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 }, smallChip: { borderColor: AppColors.hairline, borderWidth: 1, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 8 }, chipSelected: { backgroundColor: AppColors.accent, borderColor: AppColors.accentEnd }, chipText: { color: '#fff', fontSize: 13, textTransform: 'capitalize' }, chart: { backgroundColor: AppColors.surface, borderColor: AppColors.hairline, borderWidth: 1, borderRadius: 16, minHeight: 200, marginTop: 24, padding: 20, justifyContent: 'space-between' }, chartSymbol: { color: '#fff', fontSize: 18, fontWeight: '700' }, chartHint: { color: AppColors.faint, textAlign: 'center' }, price: { color: '#fff', fontSize: 28, fontWeight: '700' }, indicatorRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 }, muted: { color: AppColors.muted, fontSize: 13 }, message: { color: AppColors.muted, marginTop: 18 }, action: { backgroundColor: AppColors.accentEnd, alignItems: 'center', padding: 17, borderRadius: 24, marginTop: 20 }, stop: { backgroundColor: AppColors.danger }, actionText: { color: '#fff', fontSize: 16, fontWeight: '700' } });
