import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';
import { AppText as Text } from '@/components/app-text';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { AppColors } from '@/constants/theme';
import { api, type BrokerStatus, type Profile as ProfileData, type Session } from '@/lib/api';
import { clearTokens } from '@/lib/secure';

export default function ProfileScreen() { const [session, setSession] = useState<Session | null>(null); const [profile, setProfile] = useState<ProfileData | null>(null); const [broker, setBroker] = useState<BrokerStatus | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { Promise.all([api.getSession(), api.getProfile(), api.getBrokerStatus()]).then(([sessionResponse, profileResponse, brokerResponse]) => { setSession(sessionResponse); setProfile(profileResponse); setBroker(brokerResponse); }).finally(() => setLoading(false)); }, []); const signOut = () => clearTokens().then(() => router.replace('/welcome')); const disconnect = () => api.disconnectBybit().then(() => setBroker({ connected: false, mode: null, balance: 0 })); return <SafeAreaView style={styles.container}>{loading ? <ActivityIndicator color={AppColors.accentEnd} /> : <View><Text style={styles.title}>Profile</Text><View style={styles.avatar}><Text style={styles.avatarText}>{(profile?.username ?? session?.email ?? 'B').slice(0, 1).toUpperCase()}</Text></View><Text style={styles.name}>{profile?.username ?? 'Set your username'}</Text><Text style={styles.muted}>{session?.email}</Text><View style={styles.card}><Text style={styles.cardTitle}>Broker</Text><Text style={styles.muted}>{broker?.connected ? `${broker.mode} · $${broker.balance.toFixed(2)}` : 'Not connected'}</Text>{broker?.connected && <Pressable onPress={disconnect} style={styles.outline}><Text style={styles.danger}>Disconnect</Text></Pressable>}</View><Pressable onPress={signOut} style={styles.signOut}><Text style={styles.danger}>Sign out</Text></Pressable></View>}</SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: AppColors.background, padding: 20 }, title: { color: '#fff', fontSize: 32, fontWeight: '700', marginTop: 16, marginBottom: 28 }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: AppColors.accent, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#fff', fontSize: 28, fontWeight: '700' }, name: { color: '#fff', fontSize: 22, fontWeight: '700', marginTop: 14 }, muted: { color: AppColors.muted, fontSize: 14, marginTop: 5 }, card: { backgroundColor: AppColors.surface, borderColor: AppColors.hairline, borderWidth: 1, borderRadius: 16, padding: 18, marginTop: 32 }, cardTitle: { color: '#fff', fontSize: 17, fontWeight: '700' }, outline: { borderColor: AppColors.hairline, borderWidth: 1, borderRadius: 999, alignItems: 'center', padding: 10, marginTop: 16 }, danger: { color: AppColors.danger, fontWeight: '700' }, signOut: { alignItems: 'center', marginTop: 36, padding: 14 } });
